const { Router } = require("express");
const Categoria = require("../models/Categorias");
const Productos = require("../models/Productos");
const path = require("path");
const Carousel = require("../models/Carousel");
const jsonProductos = require("../public/jsons/productos.json");
const router = Router();

const ruta = path.join(__dirname, "../public/");

router.get("/", (req, res) => {
  res.send(index);
});
router.get("/Home", function (req, res) {
  res.sendFile(ruta + "Index.html");
});
router.get("/Categories", function (req, res) {
  res.sendFile(ruta + "categories.html");
});
router.get("/Home/Products", function (req, res) {
  res.sendFile(ruta + "products.html");
});
router.get("/AboutUs", function (req, res) {
  res.sendFile(ruta + "about-us.html");
});
router.get("/Contact", function (req, res) {
  res.sendFile(ruta + "contact.html");
});
router.get("/Sales", function (req, res) {
  res.sendFile(ruta + "sales.html");
});
router.get("/ObtenerImagenesCarrousel", function (req, res) {
  res.sendFile(ruta + "/jsons/car.json");
});
router.get("/img/carousel", function (req, res) {
  res.sendFile(ruta + "/jsons/car.json");
});

// Filtros Categorias

router.get("/OperacionCategorias/ObtenerCategorias", async function (req, res) {
  const data = await Categoria.find();
  res.json(data);
});

router.post("/OperacionCategorias/ObtenerCategoria", async function (req, res) {
  const data = await Categoria.find({ CategoriaId: req.body.id });
  res.json(data[0]);
});

router.post(
  "/OperacionCategorias/ObtenerItemsCategoria",
  async function (req, res) {
    let data = await Productos.find({ CategoriaId: req.body.id });
    res.json(data);
  }
);

router.get("/OperacionCategorias/AgregarItemNuevo", function (req, res) {
  res.sendFile(ruta + "/jsons/productos.json");
});

router.get(
  "/OperacionCategorias/AgregarImagenesItemNuevo",
  function (req, res) {
    res.sendFile(ruta + "/jsons/productos.json");
  }
);

router.get("/OperacionCategorias/EliminarItem", function (req, res) {
  res.sendFile(ruta + "/jsons/productos.json");
});

router.get("/OperacionCategorias/ObtenerItem", function (req, res) {
  res.sendFile(ruta + "/jsons/productos.json");
});

router.get("/OperacionCategorias/ModificarItem", function (req, res) {
  res.sendFile(ruta + "/jsons/productos.json");
});

// Get all posts
router.get("/posts", async (req, res) => {
  const posts = await Carousel.find();
  res.send(posts);
});

router.post("/postCar", async (req, res) => {
  const datos = [
    {
      CarouselLanding: 1,
      HomeId: "carousel-landing",
      HomeData: "./img/carousel/img-2.jpg",
    },
    {
      CarouselLanding: 2,
      HomeId: "carousel-landing",
      HomeData: "./img/carousel/img-2.jpg",
    },
    {
      CarouselLanding: 3,
      HomeId: "carousel-landing",
      HomeData: "./img/carousel/img-3.jpg",
    },
    {
      CarouselLanding: 4,
      HomeId: "carousel-landing",
      HomeData: "./img/carousel/img-4.jpg",
    },
  ];
  try {
    datos.forEach(async (dato) => {
      const carrusel = new Carousel(dato);
      await carrusel.save();
    });
    res.status(201).json("ok");
  } catch (error) {
    res.status(500).send("There was a problem");
  }
});

router.post("/postearDatos", async (req, res) => {
  const datos = [
    {
      ProyectId: 1,
      MainImageURL: "/img/projects/hondaxr150.jpg",
      Title: "Honda",
      Description: "Honda",
      ShortDescription: "XR 150",
      State: "Electrico y Patada",
      Year: 12,
      Size: 150,
      Rooms: 129,
      Address: "Honda XR 150",
      Visible: 1,
      CategoriaId: 2,
      TourURL: null,
    },
    {
      ProyectId: 2,
      MainImageURL: "/img/projects/croventriax150.jpg",
      Title: "Corven",
      Description: "Corven",
      ShortDescription: "Triax 150-250",
      State: "Electrico y Patada",
      Year: 18,
      Size: 150,
      Rooms: 125,
      Address: "Corven Triax 150-200",
      Visible: 1,
      CategoriaId: 2,
      TourURL: null,
    },
    {
      ProyectId: 3,
      MainImageURL: "/img/projects/hondatornado.jpg",
      Title: "Honda",
      Description: "Honda",
      ShortDescription: "Tornado 250",
      State: "Electrico y Patada",
      Year: 23,
      Size: 249,
      Rooms: 134,
      Address: "Honda Tornado 250",
      Visible: 1,
      CategoriaId: 2,
      TourURL: null,
    },
    {
      ProyectId: 4,
      MainImageURL: "/img/projects/corvenhunter.jpg",
      Title: "Corven",
      Description: "Corven",
      ShortDescription: "Hunter Full base",
      State: "Electrico y Patada",
      Year: 11,
      Size: 150,
      Rooms: 109,
      Address: "Corven Hunter Full base",
      Visible: 1,
      CategoriaId: 1,
      TourURL: null,
    },
    {
      ProyectId: 5,
      MainImageURL: "/img/projects/susukien125.jpg",
      Title: "Susuki",
      Description: "Susuki",
      ShortDescription: "Gn125",
      State: "Electrico y Patada",
      Year: 12,
      Size: 125,
      Rooms: 112,
      Address: "Susuki Gn125",
      Visible: 1,
      CategoriaId: 1,
      TourURL: null,
    },
    {
      ProyectId: 6,
      MainImageURL: "/img/projects/yamahaybr125.jpg",
      Title: "Yamaha",
      Description: "Yamaha",
      ShortDescription: "YBR 125",
      State: "Electrico y Patada",
      Year: 11,
      Size: 125,
      Rooms: 123,
      Address: "Yamaha YBR 125",
      Visible: 1,
      CategoriaId: 1,
      TourURL: null,
    },
    {
      ProyectId: 7,
      MainImageURL: "/img/projects/cb125.jpg",
      Title: "Honda",
      Description: "Honda",
      ShortDescription: "CB125",
      State: "Electrico y Patada",
      Year: 15,
      Size: 125,
      Rooms: 117,
      Address: "Honda CB125",
      Visible: 1,
      CategoriaId: 1,
      TourURL: null,
    },
    {
      ProyectId: 8,
      MainImageURL: "/img/projects/ProjectId_4048_ns125200414391.jpeg",
      Title: "Bajaj",
      Description: "Bajaj",
      ShortDescription: "Rouser 125",
      State: "Electrico ",
      Year: 13,
      Size: 125,
      Rooms: 122,
      Address: "Bajaj Rouser 125",
      Visible: 1,
      CategoriaId: 1,
      TourURL: null,
    },
    {
      ProyectId: 9,
      MainImageURL: "/img/projects/cg150.jpg",
      Title: "Honda",
      Description: "Honda",
      ShortDescription: "CG150",
      State: "Electrico y Patada",
      Year: 13,
      Size: 150,
      Rooms: 118,
      Address: "Honda CG150",
      Visible: 1,
      CategoriaId: 1,
      TourURL: null,
    },
    {
      ProyectId: 10,
      MainImageURL: "/img/projects/stratus150.jpg",
      Title: "Keller",
      Description: "Keller",
      ShortDescription: "Stratus 150",
      State: "Electrico y Patada",
      Year: 11,
      Size: 150,
      Rooms: 115,
      Address: "Keller Stratus 150",
      Visible: 1,
      CategoriaId: 1,
      TourURL: null,
    },
    {
      ProyectId: 11,
      MainImageURL: "/img/projects/dominar.jpg",
      Title: "Bajaj",
      Description: "Bajaj",
      ShortDescription: "Dominar",
      State: "Electrico ",
      Year: 40,
      Size: 400,
      Rooms: 184,
      Address: "Bajaj Dominar",
      Visible: 1,
      CategoriaId: 5,
      TourURL: null,
    },
    {
      ProyectId: 12,
      MainImageURL: "/img/projects/ns200.jpg",
      Title: "Bajaj",
      Description: "Bajaj",
      ShortDescription: "Ns200",
      State: "Electrico ",
      Year: 23,
      Size: 200,
      Rooms: 148,
      Address: "Bajaj Ns200",
      Visible: 1,
      CategoriaId: 5,
      TourURL: null,
    },
    {
      ProyectId: 13,
      MainImageURL: "/img/projects/ns160.jpg",
      Title: "Bajaj",
      Description: "Bajaj",
      ShortDescription: "Ns160",
      State: "Electrico ",
      Year: 16,
      Size: 160,
      Rooms: 140,
      Address: "Bajaj Ns160",
      Visible: 1,
      CategoriaId: 5,
      TourURL: null,
    },
    {
      ProyectId: 14,
      MainImageURL: "/img/projects/twister250.jpg",
      Title: "Honda",
      Description: "Honda",
      ShortDescription: "Twister 250",
      State: "Electrico ",
      Year: 22,
      Size: 250,
      Rooms: 139,
      Address: "Honda Twister 250",
      Visible: 1,
      CategoriaId: 5,
      TourURL: null,
    },
    {
      ProyectId: 15,
      MainImageURL: "/img/projects/tekken250.jpg",
      Title: "RVM",
      Description: "RVM",
      ShortDescription: "Tekken 250",
      State: "Electrico ",
      Year: 20,
      Size: 250,
      Rooms: 132,
      Address: "RVM Tekken 250",
      Visible: 1,
      CategoriaId: 5,
      TourURL: null,
    },
    {
      ProyectId: 16,
      MainImageURL: "/img/projects/energy110.jpg",
      Title: "Corven",
      Description: "Corven",
      ShortDescription: "Energy 110",
      State: "Electrico y Patada",
      Year: 7,
      Size: 110,
      Rooms: 92,
      Address: "Corven Energy 110 Base y Full",
      Visible: 1,
      CategoriaId: 4,
      TourURL: null,
    },
    {
      ProyectId: 17,
      MainImageURL: "/img/projects/mirage110.jpg",
      Title: "Corven",
      Description: "Corven",
      ShortDescription: "Mirage 110",
      State: "Electrico y Patada",
      Year: 4,
      Size: 110,
      Rooms: 104,
      Address: "Corven Mirage 110",
      Visible: 1,
      CategoriaId: 4,
      TourURL: null,
    },
    {
      ProyectId: 18,
      MainImageURL: "/img/projects/smash110.jpg",
      Title: "Gilera",
      Description: "Gilera",
      ShortDescription: "Smash Tuning",
      State: "Electrico y Patada",
      Year: 7,
      Size: 107,
      Rooms: 100,
      Address: "Gilera Smash Tuning",
      Visible: 1,
      CategoriaId: 4,
      TourURL: null,
    },
    {
      ProyectId: 19,
      MainImageURL: "/img/projects/smash125.jpg",
      Title: "Gilera",
      Description: "Gilera",
      ShortDescription: "Smash 125",
      State: "Electrico y Patada",
      Year: 7,
      Size: 125,
      Rooms: 95,
      Address: "Gilera Smash 125",
      Visible: 1,
      CategoriaId: 4,
      TourURL: null,
    },
    {
      ProyectId: 20,
      MainImageURL: "/img/projects/yamahazr115.jpg",
      Title: "Yamaha",
      Description: "Yamaha",
      ShortDescription: "ZR115",
      State: "Electrico y Patada",
      Year: 7,
      Size: 113,
      Rooms: 94,
      Address: "Yamaha ZR115",
      Visible: 1,
      CategoriaId: 3,
      TourURL: null,
    },
    {
      ProyectId: 21,
      MainImageURL: "/img/projects/agility125.jpg",
      Title: "Kymco",
      Description: "Kymco",
      ShortDescription: "Agility 125",
      State: "Electrico ",
      Year: 9,
      Size: 125,
      Rooms: 121,
      Address: "Kymco Agility 125",
      Visible: 1,
      CategoriaId: 3,
      TourURL: null,
    },
    {
      ProyectId: 22,
      MainImageURL:
        "/img/projects/ProjectId_4065_kymco-agility-200201531453.jpg",
      Title: "Kymco",
      Description: "Kymco",
      ShortDescription: "Agility200",
      State: "Electrico ",
      Year: 12,
      Size: 200,
      Rooms: 126,
      Address: "Kymco Agility200",
      Visible: 1,
      CategoriaId: 3,
      TourURL: null,
    },
    {
      ProyectId: 23,
      MainImageURL: "/img/projects/like120.jpg",
      Title: "Kymco",
      Description: "Kymco",
      ShortDescription: "Like 120 -200",
      State: "Electrico ",
      Year: 19,
      Size: 200,
      Rooms: 165,
      Address: "Kymco People 125 -200",
      Visible: 1,
      CategoriaId: 3,
      TourURL: null,
    },
    {
      ProyectId: 24,
      MainImageURL: "/img/projects/downtown300.jpg",
      Title: "Kymco",
      Description: "Kymco",
      ShortDescription: "Downtown 300",
      State: "Electrico ",
      Year: 32,
      Size: 299,
      Rooms: 189,
      Address: "Kymco Downtown 300",
      Visible: 1,
      CategoriaId: 3,
      TourURL: null,
    },
    {
      ProyectId: 25,
      MainImageURL: "/img/projects/Cascos/k3.jpg",
      Title: "Agv",
      Description: "K3",
      ShortDescription: "AGV K3 Helmet",
      State: "Casco",
      Year: 2020,
      Size: 10,
      Rooms: 12,
      Address: "Agv K3",
      Visible: 1,
      CategoriaId: 6,
      TourURL: null,
    },
    {
      ProyectId: 26,
      MainImageURL: "/img/projects/Cascos/ls2mate.jpg",
      Title: "LS2",
      Description: "380",
      ShortDescription: "LS2 380 Mate",
      State: "Casco",
      Year: 2020,
      Size: 10,
      Rooms: 12,
      Address: "LS2 380",
      Visible: 1,
      CategoriaId: 6,
      TourURL: null,
    },
    {
      ProyectId: 27,
      MainImageURL: "/img/projects/Cascos/ntr.jpg",
      Title: "ntr",
      Description: "ntr",
      ShortDescription: "ntr",
      State: "Casco",
      Year: 2020,
      Size: 10,
      Rooms: 12,
      Address: "ntr",
      Visible: 1,
      CategoriaId: 6,
      TourURL: null,
    },
    {
      ProyectId: 28,
      MainImageURL: "/img/projects/Cascos/rs5hk.jpg",
      Title: "Hawk",
      Description: "RS5",
      ShortDescription: "Hawk RS5",
      State: "Casco",
      Year: 2020,
      Size: 10,
      Rooms: 12,
      Address: "Hawk Rs5",
      Visible: 1,
      CategoriaId: 6,
      TourURL: null,
    },
    {
      ProyectId: 29,
      MainImageURL: "/img/projects/Cascos/ff320.jpg",
      Title: "LS2",
      Description: "FF320",
      ShortDescription: "LS2 FF320",
      State: "Casco",
      Year: 2020,
      Size: 10,
      Rooms: 12,
      Address: "LS2 FF320",
      Visible: 1,
      CategoriaId: 6,
      TourURL: null,
    },
    {
      ProyectId: 30,
      MainImageURL: "/img/projects/Cascos/rs11.jpg",
      Title: "Hawk",
      Description: "RS11",
      ShortDescription: "Hawk RS11",
      State: "Casco",
      Year: 2020,
      Size: 10,
      Rooms: 12,
      Address: "Hawk Rs11",
      Visible: 1,
      CategoriaId: 6,
      TourURL: null,
    },
    {
      ProyectId: 31,
      MainImageURL: "/img/projects/Cascos/ls2scooter.jpg",
      Title: "LS2",
      Description: "Scooter",
      ShortDescription: "LS2 Scooter",
      State: "Casco",
      Year: 2020,
      Size: 10,
      Rooms: 12,
      Address: "LS2 Scooter",
      Visible: 1,
      CategoriaId: 6,
      TourURL: null,
    },
    {
      ProyectId: 32,
      MainImageURL: "/img/projects/ProjectId_0_rs5hk201146864.jpg",
      Title: "Hawk RS5",
      Description: "<p>Hawk RS5<br></p>",
      ShortDescription: "Hawk RS5",
      State: "Automatico",
      Year: 12,
      Size: 123,
      Rooms: 12,
      Address: "Hawk RS5",
      Visible: 1,
      CategoriaId: 6,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 33,
      MainImageURL: "/img/projects/rtr160.jpg",
      Title: "TVS",
      Description: "RTR 160",
      ShortDescription: "TVS RTR 160 ",
      State: "Automatico",
      Year: 2020,
      Size: 160,
      Rooms: 147,
      Address: "TVS RTR 160",
      Visible: 1,
      CategoriaId: 5,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 34,
      MainImageURL: "/img/projects/rtr200.jpg",
      Title: "TVS",
      Description: "RTR 200",
      ShortDescription: "TVS RTR 200 4V 2.0",
      State: "Automatico",
      Year: 2020,
      Size: 200,
      Rooms: 149,
      Address: "TVS RTR 200 4V r 2.0",
      Visible: 1,
      CategoriaId: 5,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 35,
      MainImageURL: "/img/projects/rtr200fi.jpg",
      Title: "TVS",
      Description: "RTR 200 FI",
      ShortDescription: "TVS RTR200 FI",
      State: "Automatico",
      Year: 2020,
      Size: 200,
      Rooms: 147,
      Address: "TVS RTR 200 FI 4V R2.0",
      Visible: 1,
      CategoriaId: 5,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 36,
      MainImageURL: "/img/projects/ProjectId_4083_rrakvo203308518.jpg",
      Title: "Beta",
      Description: "200 RR Akvo",
      ShortDescription: "Beta 200 RR Akvo",
      State: "Automatico",
      Year: 2020,
      Size: 200,
      Rooms: 147,
      Address: "Beta 200 RR Akvo",
      Visible: 1,
      CategoriaId: 5,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 37,
      MainImageURL: "/img/projects/beta200akvo.jpg",
      Title: "Beta",
      Description: "200 Akbo",
      ShortDescription: "Beta 200 Akvo",
      State: "Automatico",
      Year: 2020,
      Size: 200,
      Rooms: 147,
      Address: "Beta 200 Akvo",
      Visible: 1,
      CategoriaId: 5,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 38,
      MainImageURL: "/img/projects/rr310.jpg",
      Title: "TVS",
      Description: "RR 310",
      ShortDescription: "TVS RR310",
      State: "Automatico",
      Year: 2020,
      Size: 310,
      Rooms: 169,
      Address: "TVS RR310",
      Visible: 1,
      CategoriaId: 5,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 39,
      MainImageURL: "/img/projects/zontesv310.jpg",
      Title: "Zontes",
      Description: "V310",
      ShortDescription: "Zontes V310",
      State: "Automatico",
      Year: 2020,
      Size: 310,
      Rooms: 175,
      Address: "Zontes V310",
      Visible: 1,
      CategoriaId: 5,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 40,
      MainImageURL: "/img/projects/v310rayos.jpg",
      Title: "Zontes",
      Description: "V310 Rayos",
      ShortDescription: "Zontes V310 Rayos",
      State: "Automatica",
      Year: 2020,
      Size: 310,
      Rooms: 175,
      Address: "Zontes V310 Rayos",
      Visible: 1,
      CategoriaId: 5,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 41,
      MainImageURL: "/img/projects/ProjectId_4088_torq200459375.jpg",
      Title: "TVS",
      Description: "ntorq 125",
      ShortDescription: "TVS ntorq 125",
      State: "Automatica",
      Year: 2020,
      Size: 125,
      Rooms: 116,
      Address: "TVS ntorq 125",
      Visible: 1,
      CategoriaId: 3,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 42,
      MainImageURL: "/img/projects/tempo150.jpg",
      Title: "Beta",
      Description: "Tempo 150",
      ShortDescription: "Beta Tempo 150",
      State: "Automatica",
      Year: 2020,
      Size: 150,
      Rooms: 102,
      Address: "Beta Tempo 150",
      Visible: 1,
      CategoriaId: 3,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 43,
      MainImageURL: "/img/projects/betatr20.jpg",
      Title: "Beta",
      Description: "TR 2.0",
      ShortDescription: "Beta TR 2.0",
      State: "Automatica",
      Year: 2020,
      Size: 200,
      Rooms: 120,
      Address: "Beta TR 2.0",
      Visible: 1,
      CategoriaId: 2,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 44,
      MainImageURL: "/img/projects/betatr25.jpg",
      Title: "Beta",
      Description: "TR 2.5",
      ShortDescription: "Beta TR 2.5",
      State: "Automatica",
      Year: 2020,
      Size: 250,
      Rooms: 137,
      Address: "Beta TR 2.5",
      Visible: 1,
      CategoriaId: 2,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 45,
      MainImageURL: "/img/projects/ProjectId_4092_sahel200726889.jpg",
      Title: "Gilera",
      Description: "Sahel 150",
      ShortDescription: "Gilera Sahel 150",
      State: "Automatica",
      Year: 2020,
      Size: 150,
      Rooms: 110,
      Address: "Gilera Sahel 150",
      Visible: 1,
      CategoriaId: 2,
      CreatedBy: 3,
      TourURL: null,
    },
    {
      ProyectId: 46,
      MainImageURL: "/img/projects/boxerbase.jpg",
      Title: "Corven",
      Description: "Boxer 150 Base",
      ShortDescription: "Corven Boxer 150 Base",
      State: "Automatica",
      Year: 2020,
      Size: 150,
      Rooms: 122,
      Address: "Corven Boxer 150 Base",
      Visible: 1,
      CategoriaId: 1,
      CreatedBy: 3,
      TourURL: null,
    },
  ];
  try {
    datos.forEach(async (dato) => {
      const productos = new Productos(dato);
      console.log(productos);
      await productos.save();
    });
    res.status(201).json("ok");
  } catch (error) {
    res.status(500).send("There was a problem registering the client");
  }
});

module.exports = router;
